# fly.toml app configuration file generated for voice-bot-xwgx0a on 2026-06-19
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'voice-bot-xwgx0a'
primary_region = 'gru'

[build]

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
  processes = ['app']
  size = 'shared-cpu-1x'
